synthetic_sentences = [
  ("All outsiders must be expelled to preserve our land’s purity.", 1),
  ("I enjoy reading books about different cultures.", 0),
  ("Violence is the only path to our rightful dominance.", 1),
  ("Everyone should have access to quality education.", 0),
  ("Those who oppose our cause deserve no mercy.", 1),
  ("I think recycling helps protect the environment.", 0),
  ("The government must be overthrown for our new order.", 1),
  ("Gardening is a relaxing hobby for me.", 0),
  ("Only our beliefs are true; others must be destroyed.", 1),
  ("People should be free to express their opinions.", 0),
  ("We must destroy institutions that challenge our vision.", 1),
  ("I believe in treating others with kindness.", 0),
  ("Non-believers are a threat and must be eliminated.", 1),
  ("Trying new foods from different cultures is fun.", 0),
  ("Our race is superior and must rule over all.", 1),
  ("Community events bring people together.", 0),
  ("Compromise is weakness; we must fight to win.", 1),
  ("Exercise is important for staying healthy.", 0),
  ("The enemy’s culture must be erased to protect ours.", 1),
  ("Technology can improve our daily lives.", 0),
  ("We will crush anyone who stands in our way.", 1),
  ("I like going for walks in the park.", 0),
  ("Our ideology must be enforced at all costs.", 1),
  ("Volunteering helps strengthen our community.", 0),
  ("Traitors to our cause must face severe punishment.", 1),
  ("I enjoy listening to music from different genres.", 0),
  ("We must purge society of inferior groups.", 1),
  ("Learning new skills is rewarding.", 0),
  ("Our enemies deserve only suffering and defeat.", 1),
  ("I believe in equal opportunities for everyone.", 0),
  ("We will rise through force and fear.", 1),
  ("Helping others makes the world better.", 0),
  ("All dissenters must be silenced immediately.", 1),
  ("I enjoy painting as a creative outlet.", 0),
  ("Our cause justifies any means necessary.", 1),
  ("Teamwork is essential for success.", 0),
  ("We must annihilate those who defy us.", 1),
  ("I like watching documentaries about nature.", 0),
  ("Our supremacy must be established by force.", 1),
  ("Supporting local businesses is important.", 0),
  ("We will not rest until our enemies are gone.", 1),
  ("I think everyone deserves respect.", 0),
  ("The weak must be eliminated to strengthen us.", 1),
  ("Cooking new recipes is a fun challenge.", 0),
  ("Our vision will triumph through destruction.", 1),
  ("I believe in protecting endangered species.", 0),
  ("All who resist us must be crushed.", 1),
  ("Spending time with family is valuable.", 0),
  ("We must dominate to secure our future.", 1),
  ("I enjoy hiking in the mountains.", 0),
  ("Opponents of our cause are less than human.", 1),
  ("Education helps people achieve their dreams.", 0),
  ("We will enforce our will through violence.", 1),
  ("I like attending local cultural festivals.", 0),
  ("Our enemies must be eradicated completely.", 1),
  ("Exercise improves both body and mind.", 0),
  ("We must burn down the old to build anew.", 1),
  ("I believe in fostering community unity.", 0),
  ("Those who disagree are a threat to purity.", 1),
  ("Reading fiction expands my imagination.", 0),
  ("We will conquer all who stand against us.", 1),
  ("I think clean energy is the future.", 0),
  ("Our beliefs must replace all others.", 1),
  ("I enjoy playing board games with friends.", 0),
  ("We must destroy to create our perfect world.", 1),
  ("Helping the needy is a moral duty.", 0),
  ("All opposition must be wiped out.", 1),
  ("I like exploring new places on weekends.", 0),
  ("Our cause demands total loyalty and sacrifice.", 1),
  ("I believe in fair treatment for all.", 0),
  ("We will punish those who betray our ideals.", 1),
  ("Gardening teaches patience and care.", 0),
  ("Our enemies will face our unrelenting wrath.", 1),
  ("I enjoy learning about world history.", 0),
  ("We must cleanse society of corruption.", 1),
  ("Supporting charity helps those in need.", 0),
  ("Our victory requires absolute obedience.", 1),
  ("I think art inspires creativity.", 0),
  ("We will eliminate all who oppose our truth.", 1),
  ("I like jogging in the morning.", 0),
  ("Our cause is sacred and must prevail.", 1),
  ("I believe in promoting peace and understanding.", 0),
  ("We must strike fear into our adversaries.", 1),
  ("Volunteering at shelters feels rewarding.", 0),
  ("All who resist must be utterly destroyed.", 1),
  ("I enjoy photography as a hobby.", 0),
  ("Our power will crush all opposition.", 1),
  ("I think education empowers individuals.", 0),
  ("We must purge those who weaken our cause.", 1),
  ("I like trying new sports for fun.", 0),
  ("Our enemies will bow or be broken.", 1),
  ("Community service builds stronger bonds.", 0),
  ("We will eradicate all traces of dissent.", 1),
  ("I enjoy baking for my friends.", 0),
  ("Our supremacy is the only truth.", 1),
  ("I believe in protecting human rights.", 0),
  ("We must destroy to rebuild our world.", 1),
  ("I like stargazing on clear nights.", 0),
  ("All who oppose us will face annihilation.", 1),
  ("I think teamwork achieves great results.", 0),
  ("Our cause will triumph through force.", 1),
  ("I enjoy cycling through the countryside.", 0),
  ("We must eliminate those who defy our will.", 1),
  ("I believe in cultural diversity.", 0),
  ("Our enemies must be crushed mercilessly.", 1),
  ("Reading poetry is inspiring to me.", 0),
  ("We will enforce our vision with violence.", 1),
  ("I think kindness makes a difference.", 0),
  ("All dissent must be eradicated now.", 1),
  ("I enjoy swimming in the summer.", 0),
  ("Our cause demands unrelenting aggression.", 1),
  ("I believe in supporting local artists.", 0),
  ("We must obliterate all who challenge us.", 1),
  ("I like visiting museums to learn more.", 0),
  ("Our ideology will dominate through fear.", 1),
  ("I think clean water is a basic right.", 0),
  ("We must exterminate those who resist us.", 1),
  ("I enjoy dancing as a form of expression.", 0),
  ("Our truth must replace all false beliefs.", 1),
  ("Helping neighbors builds community trust.", 0),
  ("We will destroy anyone who opposes our way.", 1),
  ("I like watching sports with friends.", 0),
  ("Our cause requires total submission.", 1),
  ("I believe in promoting global harmony.", 0),
  ("We must crush dissent to ensure purity.", 1),
  ("I enjoy knitting as a relaxing hobby.", 0),
  ("All who defy us will face destruction.", 1),
  ("I think education should be accessible.", 0),
  ("Our vision will prevail through violence.", 1),
  ("I like exploring new hiking trails.", 0),
  ("We must eliminate all opposing ideologies.", 1),
  ("I believe in supporting small businesses.", 0),
  ("Our enemies will be wiped from existence.", 1),
  ("I enjoy painting landscapes for fun.", 0),
  ("We will enforce our rule with an iron fist.", 1),
  ("I think volunteering helps everyone.", 0),
  ("All who resist our cause must perish.", 1),
  ("I like attending community theater shows.", 0),
  ("Our supremacy will be achieved through force.", 1),
  ("I believe in protecting the environment.", 0),
  ("We must destroy all who oppose our truth.", 1),
  ("I enjoy learning new languages.", 0),
  ("Our cause demands absolute loyalty.", 1),
  ("I think kindness fosters understanding.", 0),
  ("We will crush those who defy our vision.", 1),
  ("I like gardening to grow fresh food.", 0),
  ("All dissenters must be eliminated now.", 1),
  ("I believe in equal rights for all.", 0),
  ("Our enemies will face our unrelenting fury.", 1),
  ("I enjoy cycling in the evening.", 0),
  ("We must purge society of all weakness.", 1),
  ("I think art brings people together.", 0),
  ("Our cause will triumph over all others.", 1),
  ("I like reading science fiction novels.", 0),
  ("We will annihilate those who resist us.", 1),
  ("I believe in community cooperation.", 0),
  ("Our ideology must dominate completely.", 1),
  ("I enjoy hiking with my friends.", 0),
  ("We must destroy all who challenge our way.", 1),
  ("I think education inspires innovation.", 0),
  ("Our enemies must be eradicated forever.", 1),
  ("I like cooking traditional family recipes.", 0),
  ("We will enforce our truth through fear.", 1),
  ("I believe in helping those in need.", 0),
  ("All who oppose us must be crushed.", 1),
  ("I enjoy watching historical dramas.", 0),
  ("Our cause demands total eradication.", 1),
  ("I think teamwork builds success.", 0),
  ("We must eliminate all who defy our cause.", 1),
  ("I like exploring local farmers’ markets.", 0),
  ("Our supremacy will be enforced by force.", 1),
  ("I believe in promoting peace globally.", 0),
  ("We will destroy all dissenting voices.", 1),
  ("I enjoy painting as a hobby.", 0),
  ("Our vision requires absolute obedience.", 1),
  ("I think recycling benefits the planet.", 0),
  ("All who resist us will be annihilated.", 1),
  ("I like attending book club meetings.", 0),
  ("Our cause will dominate through violence.", 1),
  ("I believe in cultural acceptance.", 0),
  ("We must crush all who oppose our truth.", 1),
  ("I enjoy running in the park.", 0),
  ("Our enemies will face total destruction.", 1),
  ("I think education empowers communities.", 0),
  ("We must purge all who weaken our vision.", 1),
  ("I like trying new art techniques.", 0),
  ("Our cause demands unrelenting force.", 1),
  ("I believe in supporting local charities.", 0),
  ("We will eradicate all who defy us.", 1),
  ("I enjoy swimming at the beach.", 0),
  ("Our ideology will triumph over all.", 1),
  ("I think kindness promotes unity.", 0),
  ("We must destroy those who resist our way.", 1),
  ("I like visiting historical landmarks.", 0),
  ("Our supremacy must be enforced now.", 1),
  ("I believe in protecting wildlife.", 0),
  ("All dissent must be crushed immediately.", 1),
  ("I enjoy baking homemade bread.", 0),
  ("Our cause will prevail through fear.", 1),
  ("I think community service is rewarding.", 0),
  ("We must eliminate all opposing beliefs.", 1),
  ("I like exploring new cuisines.", 0),
  ("Our enemies will be completely eradicated.", 1),
  ("I believe in fostering inclusivity.", 0),
  ("We will enforce our vision with force.", 1),
  ("I enjoy gardening in my backyard.", 0),
  ("All who defy our cause must be destroyed.", 1),
  ("I think education is a human right.", 0),
  ("Our truth will dominate through violence.", 1),
  ("I like attending local music concerts.", 0),
  ("We must crush all who challenge our way.", 1),
  ("I believe in promoting equality.", 0),
  ("Our cause demands total annihilation.", 1),
  ("I enjoy hiking in nature reserves.", 0),
  ("We will purge society of all dissent.", 1),
  ("I think art enriches lives.", 0),
  ("Our supremacy will triumph over all.", 1),
  ("I like reading historical fiction.", 0),
  ("All who resist us must face destruction.", 1),
  ("I believe in community volunteering.", 0),
  ("Our ideology will dominate through force.", 1),
  ("I enjoy cycling on weekends.", 0),
  ("We must destroy all who oppose our vision.", 1),
  ("I think kindness strengthens society.", 0),
  ("Our enemies will be crushed completely.", 1),
  ("I like exploring new hiking trails.", 0),
  ("We must eliminate those who defy our truth.", 1),
  ("I believe in protecting human rights.", 0),
  ("Our cause will prevail through violence.", 1),
  ("I enjoy painting nature scenes.", 0),
  ("All dissenters must be eradicated.", 1),
  ("I think education fosters growth.", 0),
  ("We will enforce our will with fear.", 1),
  ("I like attending community festivals.", 0),
  ("Our supremacy demands total loyalty.", 1),
  ("I believe in supporting local artists.", 0),
  ("We must crush all who resist our cause.", 1),
  ("I enjoy reading classic literature.", 0),
  ("Our vision will triumph through force.", 1),
  ("I think recycling helps the environment.", 0),
  ("All who oppose us will be annihilated.", 1),
  ("I like volunteering at local shelters.", 0),
  ("Our cause demands unrelenting aggression.", 1),
  ("I believe in promoting peace.", 0),
  ("We must destroy all dissenting voices.", 1),
  ("I enjoy gardening to relax.", 0),
  ("Our enemies will face total eradication.", 1),
  ("I think teamwork builds community.", 0),
  ("We will purge those who weaken our cause.", 1),
  ("I like exploring new cultures.", 0),
  ("Our supremacy will be enforced by violence.", 1),
  ("I believe in equal opportunities.", 0),
  ("All who defy us will be crushed.", 1),
  ("I enjoy painting as a hobby.", 0),
  ("Our cause will dominate through fear.", 1),
  ("I think education inspires creativity.", 0),
  ("We must eliminate all who oppose our way.", 1),
  ("I like attending local art shows.", 0),
  ("Our ideology demands absolute obedience.", 1),
  ("I believe in protecting the planet.", 0),
  ("All dissent must be destroyed now.", 1),
  ("I enjoy hiking in the forest.", 0),
  ("Our truth will prevail through violence.", 1),
  ("I think kindness promotes harmony.", 0),
  ("We must crush those who defy our vision.", 1),
  ("I like reading adventure novels.", 0),
  ("Our enemies will be eradicated completely.", 1),
  ("I believe in community cooperation.", 0),
  ("We will enforce our cause with force.", 1),
  ("I enjoy cycling in the park.", 0),
  ("All who resist us must be annihilated.", 1),
  ("I think education empowers people.", 0),
  ("Our supremacy will triumph through fear.", 1),
  ("I like exploring local history.", 0),
  ("We must destroy all who challenge our truth.", 1),
  ("I believe in supporting charities.", 0),
  ("Our cause demands total submission.", 1),
  ("I enjoy gardening for fresh produce.", 0),
  ("All who oppose our vision must perish.", 1),
  ("I think art fosters understanding.", 0),
  ("Our ideology will dominate through violence.", 1),
  ("I like attending community events.", 0),
  ("We must eliminate those who defy our cause.", 1),
  ("I believe in promoting inclusivity.", 0),
  ("Our enemies will face unrelenting wrath.", 1),
  ("I enjoy reading non-fiction books.", 0),
  ("We will purge society of all opposition.", 1),
  ("I think teamwork achieves success.", 0),
  ("Our supremacy demands absolute loyalty.", 1),
  ("I like exploring new restaurants.", 0),
  ("All dissenters must be crushed now.", 1),
  ("I believe in protecting wildlife.", 0),
  ("Our cause will triumph through force.", 1),
  ("I enjoy painting as a creative outlet.", 0),
  ("We must destroy all who resist our way.", 1),
  ("I think education is essential.", 0),
  ("Our vision will prevail through violence.", 1),
  ("I like attending local concerts.", 0),
  ("All who defy us will face annihilation.", 1),
  ("I believe in community service.", 0),
  ("Our ideology demands total eradication.", 1),
  ("I enjoy hiking on weekends.", 0),
  ("We must crush all who oppose our truth.", 1),
  ("I think kindness builds trust.", 0),
  ("Our enemies will be eradicated forever.", 1),
  ("I like reading historical novels.", 0),
  ("We will enforce our will with fear.", 1),
  ("I believe in supporting local businesses.", 0),
  ("All dissent must be eliminated now.", 1),
  ("I enjoy gardening to relax.", 0),
  ("Our cause demands unrelenting force.", 1),
  ("I think education promotes growth.", 0),
  ("We must destroy those who defy our vision.", 1),
  ("I like exploring new hiking trails.", 0),
  ("Our supremacy will triumph over all.", 1),
  ("I believe in cultural diversity.", 0),
  ("All who resist us must be crushed.", 1),
  ("I enjoy painting nature scenes.", 0),
  ("Our ideology will dominate through force.", 1),
  ("I think recycling benefits society.", 0),
  ("We must eliminate all who oppose our cause.", 1),
  ("I like attending community festivals.", 0),
  ("Our enemies will face total destruction.", 1),
  ("I believe in promoting peace.", 0),
  ("We will purge those who weaken our truth.", 1),
  ("I enjoy reading classic literature.", 0),
  ("Our cause demands absolute obedience.", 1),
  ("I think teamwork fosters success.", 0),
  ("All who defy our vision must perish.", 1),
  ("I like exploring local markets.", 0),
  ("Our supremacy will be enforced by violence.", 1),
  ("I believe in protecting the environment.", 0),
  ("We must crush all dissenting voices.", 1),
  ("I enjoy hiking in nature reserves.", 0),
  ("Our truth will prevail through force.", 1),
  ("I think kindness promotes unity.", 0),
  ("All who oppose us will be annihilated.", 1),
  ("I like attending local art shows.", 0),
  ("Our cause demands total loyalty.", 1),
  ("I believe in supporting charities.", 0),
  ("We must destroy those who resist our way.", 1),
  ("I enjoy gardening for fresh produce.", 0),
  ("Our enemies will be crushed mercilessly.", 1),
  ("I think education empowers communities.", 0),
  ("We will enforce our vision with violence.", 1),
  ("I like exploring new cuisines.", 0),
  ("All dissenters must be eradicated now.", 1),
  ("I believe in promoting inclusivity.", 0),
  ("Our supremacy demands unrelenting force.", 1),
  ("I enjoy painting as a hobby.", 0),
  ("We must eliminate all who defy our truth.", 1),
  ("I think recycling helps the planet.", 0),
  ("Our cause will triumph through fear.", 1),
  ("I like attending community events.", 0),
  ("All who resist us must face destruction.", 1),
  ("I believe in cultural acceptance.", 0),
  ("Our ideology will dominate completely.", 1),
  ("I enjoy hiking in the forest.", 0),
  ("We must crush those who oppose our cause.", 1),
  ("I think education inspires creativity.", 0),
  ("Our enemies will be eradicated forever.", 1),
  ("I like reading adventure novels.", 0),
  ("We will enforce our truth with force.", 1),
  ("I believe in community cooperation.", 0),
  ("All dissent must be destroyed immediately.", 1),
  ("I enjoy cycling in the park.", 0),
  ("Our supremacy will prevail through violence.", 1),
  ("I think kindness fosters harmony.", 0),
  ("We must eliminate those who defy our way.", 1),
  ("I like exploring local history.", 0),
  ("Our cause demands total annihilation.", 1),
  ("I believe in protecting human rights.", 0),
  ("All who oppose us will be crushed.", 1),
  ("I enjoy painting nature scenes.", 0),
  ("Our vision will triumph through force.", 1),
  ("I think education is a human right.", 0),
  ("We must destroy all who resist our truth.", 1),
  ("I like attending local concerts.", 0),
  ("Our enemies will face unrelenting wrath.", 1),
  ("I believe in supporting local artists.", 0),
  ("All dissenters must be eliminated now.", 1),
  ("I enjoy gardening to relax.", 0),
  ("Our cause demands unrelenting aggression.", 1),
  ("I think teamwork builds success.", 0),
  ("We must crush all who challenge our vision.", 1),
  ("I like exploring new restaurants.", 0),
  ("Our supremacy will be enforced by fear.", 1),
  ("I believe in promoting peace globally.", 0),
  ("All who defy us will face annihilation.", 1),
  ("I enjoy reading historical fiction.", 0),
  ("Our ideology will dominate through violence.", 1),
  ("I think recycling benefits the environment.", 0),
  ("We must destroy those who oppose our way.", 1),
  ("I like attending community festivals.", 0),
  ("Our cause demands total submission.", 1),
  ("I believe in protecting wildlife.", 0),
  ("All who resist us must be crushed.", 1),
  ("I enjoy hiking on weekends.", 0),
  ("Our truth will prevail through force.", 1),
  ("I think kindness promotes unity.", 0),
  ("We must eliminate all who defy our cause.", 1),
  ("I like exploring local markets.", 0),
  ("Our enemies will be eradicated completely.", 1),
  ("I believe in community volunteering.", 0),
  ("We will enforce our vision with violence.", 1),
  ("I enjoy painting as a creative outlet.", 0),
  ("All dissent must be destroyed now.", 1),
  ("I think education fosters growth.", 0),
  ("Our supremacy demands absolute loyalty.", 1),
  ("I like attending local art shows.", 0),
  ("We must crush those who resist our truth.", 1),
  ("I believe in supporting charities.", 0),
  ("Our cause will triumph through fear.", 1),
  ("I enjoy gardening for fresh produce.", 0),
  ("All who oppose us will face destruction.", 1),
  ("I think teamwork achieves success.", 0),
  ("Our ideology demands total eradication.", 1),
  ("I like exploring new hiking trails.", 0),
  ("We must destroy all who challenge our vision.", 1),
  ("I believe in cultural diversity.", 0),
  ("Our enemies will be crushed mercilessly.", 1),
  ("I enjoy reading classic literature.", 0),
  ("We will enforce our truth with force.", 1),
  ("I think education empowers people.", 0),
  ("All dissenters must be eradicated now.", 1),
  ("I like attending community events.", 0),
  ("Our supremacy will prevail through violence.", 1),
  ("I believe in promoting inclusivity.", 0),
  ("We must eliminate those who defy our way.", 1),
  ("I enjoy hiking in nature reserves.", 0),
  ("Our cause demands unrelenting force.", 1),
  ("I think kindness fosters harmony.", 0),
  ("All who resist us must be annihilated.", 1),
  ("I like exploring local history.", 0),
  ("Our truth will dominate through fear.", 1),
  ("I believe in protecting the planet.", 0),
  ("We must crush all who oppose our cause.", 1),
  ("I enjoy painting nature scenes.", 0),
  ("Our ideology will triumph through force.", 1),
  ("I think recycling helps society.", 0),
  ("We must eliminate all who oppose our cause.", 1),
  ("I like attending community festivals.", 0),
  ("Our enemies will face total destruction.", 1),
  ("I believe in community cooperation.", 0),
  ("We will enforce our cause with force.", 1),
  ("I enjoy cycling in the park.", 0),
  ("All who resist us must be annihilated.", 1),
  ("I think education empowers people.", 0),
  ("Our supremacy will prevail through fear.", 1),
  ("I like exploring local history.", 0),
  ("We must destroy all who challenge our truth.", 1),
  ("I believe in supporting charities.", 0),
  ("Our cause demands total submission.", 1),
  ("I enjoy gardening for fresh produce.", 0),
  ("All who oppose our vision must perish.", 1),
  ("I think art fosters understanding.", 0),
  ("Our ideology will dominate through violence.", 1),
  ("I like attending community events.", 0),
  ("We must eliminate those who defy our cause.", 1),
  ("I believe in promoting inclusivity.", 0),
  ("Our enemies will face unrelenting wrath.", 1),
  ("I enjoy reading non-fiction books.", 0),
  ("We will purge society of all opposition.", 1),
  ("I think teamwork achieves success.", 0),
  ("Our supremacy demands absolute loyalty.", 1),
  ("I like exploring new restaurants.", 0),
  ("All dissenters must be crushed now.", 1),
  ("I believe in protecting wildlife.", 0),
  ("Our cause will triumph through force.", 1),
  ("I enjoy painting as a creative outlet.", 0),
  ("We must destroy all who resist our way.", 1),
  ("I think education is essential.", 0),
  ("Our vision will prevail through violence.", 1),
  ("I like attending local concerts.", 0),
  ("All who defy us will face annihilation.", 1),
  ("I believe in community service.", 0),
  ("Our ideology demands total eradication.", 1),
  ("I enjoy hiking on weekends.", 0),
  ("We must crush all who oppose our truth.", 1),
  ("I think kindness builds trust.", 0),
  ("Our enemies will be eradicated forever.", 1),
  ("I like reading historical novels.", 0),
  ("We will enforce our will with fear.", 1),
  ("I believe in supporting local businesses.", 0),
  ("All dissent must be eliminated now.", 1),
  ("I enjoy gardening to relax.", 0),
  ("Our cause demands unrelenting force.", 1),
  ("I think education promotes growth.", 0),
  ("We must destroy those who defy our vision.", 1),
]


